n = input('Digite algo: ')
print('O tipo primitivo é', type(n))
print('Só tem espaços:', n.isspace())
print('É alfabético:', n.isalpha())
print('É numérico:', n.isnumeric())
print('É alfanumérico:', n.isalnum())
print('É em minúsculo:', n.islower())
print('É em maiúsculo:', n.isupper())
print('Está capitalizada:', n.istitle())
